### ISSUE TITLE
Feature: define task reqs for typical openquake job

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-toshi-api#68]
**We want** to run openquake tasks using nzshm-runzi (automation) and collect job metadata, inputs, outputs etc in toshi-api

**So that** we have history etc avail to the team. 

Epic: https://github.com/orgs/GNS-Science/projects/9#card-67029920

Needed: 
 - [x] list of inputs for a typical openquake task
 - [x] list of cmd-line arguments that are supplied to run the job 
 - [x] list any environment settings needed? 
 - [x] list of typical outputs
 - [x] supply examples of input/outputs

**Comment by thingbaijam** [comment]
**List of inputs for a typical OQ task**

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-765d9685-7fff-4424-4d6c-19c3d6c26f8d">

Input | Format | Remarks
-- | -- | --
Configuration | *.ini | This file informs OQ of metadata, where to locate the inputs (as listed below), where/how to generate outputs, and other specifications (viz., those relevant to site conditions, maximum source-to-site distance, intensity measure types, etc) . The format follows OQ specification.Instead of an input file, sites can be alternatively specified as a polygon with grid-spacing. But, using *.csv file is preferable.
Sites (or locations) | *. csv | Comma separated rows of longitude and latitudes (both in degrees).  Sites can be grid locations or some selected ones. The generation of spatial hazard maps would optimally require grids. Some sites could be identified according to perceptible significant risk such as those in Christchurch, Wellington, Auckland, etc. That would facilitate examining site-targeted evaluation.
Source model | *.xml | An xml file containing the description of the source models. It incorporate an hierarchical sort of representation such that source model is given in another *.xml file.
Ground motion model | *.xml | This file contains the list of ground motion models (GMMs). The details include assigned weight and which type of tectonic region to apply for each GMM.
Site parameters | *.csv | This input file can be used for spatially varying soil properties. This is an alternative to specifying uniform site conditions in the configuration file.   The file has the structure:lon, lat, vs30, z1pt0, z2pt5, vs30measured, backarc

</div><br />

**List of cmd-line arguments that are supplied to run the job**

The simplest command API on a terminal is:
oq engine --run [some_input_file.ini] 

Often, we use --export flag to specify output format.

**List any environment settings needed**
Main dependencies are:
Python 3.6+ (3.7+ is preferable)
Django - Used by the OQ API server and the WebUI 
HDF5 - Used for storing and managing data 
numpy and scipy - Fundamental packages for scientific computing with Python
pyzmq - Used for internal inter-process communications

A few useful links 
_Hardware considerations_
https://github.com/gem/oq-engine/blob/master/doc/adv-manual/oq-commands.rst
https://github.com/gem/oq-engine/blob/master/doc/hardware-suggestions.md

_Installing on Linux Cluster_
A guide can be found here:
https://github.com/gem/oq-engine/blob/master/doc/installing/cluster.md

_Software stack for OQ_ 
https://github.com/gem/oq-engine/blob/master/doc/requirements.md

**List of typical outputs**

The results from the OQ engine can be obtained directly or by exporting them from the internal oq-engine database (**HDF5**) after the calculation is completed.  The former approach involves the “-exports” flag in the command.  

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-2434afea-7fff-2a65-1e31-45b6102c0b33">

Output | Format | Remarks
-- | -- | --
Hazard curve | *.csv | This file contains the hazard curve computed at each site. The contents are described in a two-lines header.
Hazard Map | *.csv | The file provides the calculated hazard for each site. As with hazard curves, the contents are described in a two-lines header.

</div><br />
Note: outputs can be also exported in XML (or NRML) formats.
